server:
  port: 0
  
spring:
  application:
    name: store-order
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/poo
    username: postgres
    password: Post123321
    driver-class-name: org.postgresql.Driver
    # driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}